import type { Metadata } from "next";

import "./globals.css";
import localFont from "next/font/local";
import Header from "@/src/components/Header";
import Footer from "@/src/components/Footer";
import ScrollBar from "@/src/components/ScrollBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const pretendard = localFont({
  src: [
    {
      path: "../public/fonts/Pretendard-Bold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../public/fonts/Pretendard-Medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/Pretendard-Light.otf",
      weight: "300",
      style: "normal",
    },
  ],
  variable: "--font-pretendard",
  display: "swap",
});

const sfMono = localFont({
  src: [
    {
      path: "../public/fonts/SFMONO-Bold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../public/fonts/SFMono-Medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/SFMono-Light.otf",
      weight: "300",
      style: "normal",
    },
  ],
  variable: "--font-sf-mono",
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`${sfMono.className} ${pretendard.className} font-sans bg-[#EFEEEA]`}
      >
        <Header />

        {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
